Base.show(io::IO, tl::AbstractTransmissionLine) = print(io, 
                                                    "Transmission Line Data:",
                                                    "\n    basicdata: ", typeof(tl.basicdata),
                                                    "\n        - voltage_kv: ", tl.basicdata.voltage_kv,
                                                    "\n        - n_circuits: ", tl.basicdata.n_circuits,
                                                    "\n        - structure_code: ", tl.basicdata.structure_code,
                                                    "\n    geometry: ", typeof(tl.geometry),
                                                    "\n    conductor: ", typeof(tl.conductor),
                                                    "\n        - type: ", tl.conductor.type,
                                                    "\n        - codeword: ", tl.conductor.codeword,
                                                    "\n        - stranding: ", tl.conductor.stranding,
                                                    "\n        - kcmil: ", tl.conductor.kcmil,
                                                    "\n    groundwire: ", typeof(tl.groundwire),
                                                    "\n        - type: ", tl.groundwire.type,
                                                    "\n        - awg: ", tl.groundwire.awg,
                                                    "\n        - kcmil: ", tl.groundwire.kcmil,
                                                    "\n    parameters: ", typeof(tl.parameters),
                                                    "\n        - r1: ", tl.parameters.r1,
                                                    "\n        - x1: ", tl.parameters.x1,
                                                    "\n        - b1: ", tl.parameters.b1,
                                                    "\n"
                                                     )

Base.show(io::IO, basic_data::TLBasicData) = print(io, 
                                                    "Transmission Line Basic Data:",
                                                    "\n    name: ", basic_data.name,
                                                    "\n    voltage_kv: ", basic_data.voltage_kv,
                                                    "\n    n_circuits: ", basic_data.n_circuits,
                                                    "\n    n_ground_wire: ", basic_data.n_ground_wire,
                                                    "\n    state: ", basic_data.state,
                                                    "\n    structure_type: ", basic_data.structure_type,
                                                    "\n    structure_code: ", basic_data.structure_code,
                                                    "\n    distance: ", basic_data.distance,
                                                    "\n    S_rated: ", basic_data.S_rated,
                                                    "\n    frequency: ", basic_data.frequency,
                                                    "\n    gnd_rho: ", basic_data.gnd_rho,
                                                    "\n"
                                                     )

Base.show(io::IO, geometry::TLGeometry) = print(io, 
                                                    "Transmission Line Geometry Data:",
                                                    "\n    n_cables: ", geometry.n_cables,
                                                    "\n    x_coordinates: ", geometry.x_coordinates,
                                                    "\n    y_coordinates: ", geometry.y_coordinates,
                                                    "\n    combinations: ", geometry.combinations,
                                                    "\n    distances: ", geometry.distances,
                                                    "\n"
                                                     )

Base.show(io::IO, conductor::TLConductor) = print(io, 
                                                    "Transmission Conductor Data:",
                                                    "\n    type: ", conductor.type,
                                                    "\n    codeword: ", conductor.codeword,
                                                    "\n    stranding: ", conductor.stranding,
                                                    "\n    kcmil: ", conductor.kcmil,
                                                    "\n    diameter: ", conductor.diameter,
                                                    "\n    gmr: ", conductor.gmr,
                                                    "\n    Rac_tnom: ", conductor.Rac_tnom,
                                                    "\n    XLinternal: ", conductor.XLinternal,
                                                    "\n    XCinternal: ", conductor.XCinternal,
                                                    "\n    ampacity: ", conductor.ampacity,
                                                    "\n    bundling: ", conductor.bundling,
                                                    "\n    bundlingspacing: ", conductor.bundlingspacing,
                                                    "\n    bundling_xcoordinates: ", conductor.bundling_xcoordinates,
                                                    "\n    bundling_ycoordinates: ", conductor.bundling_ycoordinates,
                                                    "\n    gmr_bundling: ", conductor.gmr_bundling,
                                                    "\n    XL_bundling: ", conductor.XL_bundling,
                                                    "\n    r_ft_c_bundling: ", conductor.r_ft_c_bundling,
                                                    "\n    XC_bundling: ", conductor.XC_bundling,
                                                    "\n    ampacity_bundling: ", conductor.ampacity_bundling,
                                                    "\n"
                                                     )

Base.show(io::IO, ground_wire::TLGroundWire) = print(io, 
                                                    "Transmission Line Ground Wire Data:",
                                                    "\n    type: ", ground_wire.type,
                                                    "\n    awg: ", ground_wire.awg,
                                                    "\n    kcmil: ", ground_wire.kcmil,
                                                    "\n    diameter: ", ground_wire.diameter,
                                                    "\n    gmr: ", ground_wire.gmr,
                                                    "\n    Rdc_20: ", ground_wire.Rdc_20,
                                                    "\n    XLinternal: ", ground_wire.XLinternal,
                                                    "\n    XCinternal: ", ground_wire.XCinternal,
                                                    "\n"
                                                     )

Base.show(io::IO, parameter::ElectricalParameters) = print(io, 
                                                    "Transmission Conductor Data:",
                                                    "\n    Zabcg: ", typeof(parameter.Zabcg),
                                                    "\n    Z_kron_nt: ", typeof(parameter.Z_kron_nt),
                                                    "\n    Z012_nt: ", typeof(parameter.Z012_nt),
                                                    "\n    Z_kron_ft: ", typeof(parameter.Z_kron_ft),
                                                    "\n    Z012_ft: ", typeof(parameter.Z012_ft),
                                                    "\n    Y_kron_nt: ", typeof(parameter.Y_kron_nt),
                                                    "\n    Y012_nt: ", typeof(parameter.Y012_nt),
                                                    "\n    Y_kron_ft: ", typeof(parameter.Y_kron_ft),
                                                    "\n    Y012_ft: ", typeof(parameter.Y012_ft),
                                                    "\n    r1: ", parameter.r1,
                                                    "\n    x1: ", parameter.x1,
                                                    "\n    b1: ", parameter.b1,
                                                    "\n    r0: ", parameter.r0,
                                                    "\n    x0: ", parameter.x0,
                                                    "\n    b0: ", parameter.b0,
                                                    "\n    r0m: ", parameter.r0m,
                                                    "\n    x0m: ", parameter.x0m,
                                                    "\n    b0m: ", parameter.b0m,
                                                    "\n    Z_sil: ", parameter.Z_sil,
                                                    "\n    sil: ", parameter.sil,
                                                    "\n"
                                                     )
